"""Turn what the GUI is showing into a Python script that reproduces it.

Clicking is fast for looking; a script is what you keep. Every plotting page can
hand over the code behind the figure on screen, so the next step — a different
normalization, an inset, a fit, a panel the GUI does not offer — starts from
working code instead of a blank cell.

The generated scripts use only the public API (:mod:`pyscattviz.plotting`,
:mod:`pyscattviz.dataio`, :mod:`pyscattviz.publication`), so they run in a
notebook, from a terminal, or in the application's own Python console.

Everything here is pure text generation: no Streamlit, no filesystem, no
plotting. That keeps it testable, and it means the code shown is exactly the
code you get.
"""

from __future__ import annotations

from collections.abc import Sequence

__all__ = [
    "curve_overlay_code",
    "matplotlib_cmap",
    "frame_panel_code",
    "image_code",
    "publication_code",
    "stack_code",
]

_HEADER = "# Generated by pyScattViz. Everything below uses the public API.\n"

# The 2D panels are drawn with Plotly, whose colormap names are not matplotlib's.
# A generated script is matplotlib, so translate rather than emit a name that
# raises the moment anyone runs it.
_MATPLOTLIB_CMAP = {
    "turbo": "turbo",
    "viridis": "viridis",
    "inferno": "inferno",
    "magma": "magma",
    "plasma": "plasma",
    "cividis": "cividis",
    "jet": "jet",
    "hot": "hot",
    "rainbow": "rainbow",
    "spectral": "Spectral",
    "ice": "Blues",
    "thermal": "inferno",
    "portland": "coolwarm",
    "electric": "hot",
    "blackbody": "afmhot",
}


def matplotlib_cmap(name: str) -> str:
    """Translate a Plotly colormap name to the nearest matplotlib one."""

    return _MATPLOTLIB_CMAP.get(str(name).strip().lower(), "viridis")


def _literal(value) -> str:
    """Render a value as Python source."""

    if isinstance(value, str):
        return repr(value)
    if value is None or isinstance(value, (bool, int, float)):
        return repr(value)
    if isinstance(value, (list, tuple)):
        return "[" + ", ".join(_literal(item) for item in value) + "]"
    return repr(value)


def _path_list(paths: Sequence[str], name: str = "paths") -> str:
    """Render a list of full paths one per line, which stays readable."""

    if not paths:
        return f"{name} = []\n"
    body = "\n".join(f"    {_literal(str(item))}," for item in paths)
    return f"{name} = [\n{body}\n]\n"


def _script(*blocks: str) -> str:
    return _HEADER + "\n" + "\n".join(block.rstrip() + "\n" for block in blocks if block)


def curve_overlay_code(
    paths: Sequence[str],
    *,
    x_column: str | None = None,
    y_column: str | None = None,
    normalization: str = "none",
    reference_x: float = 0.1,
    offset: float = 0.0,
    multiplier: float = 1.0,
    log_x: bool = True,
    log_y: bool = True,
    x_min: float | None = None,
    x_max: float | None = None,
    title: str = "",
    xlabel: str = "q ($\\AA^{-1}$)",
    ylabel: str = "I(q)",
) -> str:
    """Return a script that overlays the selected 1D curves."""

    imports = (
        "import matplotlib.pyplot as plt\n"
        "import numpy as np\n"
        "\n"
        "import pyscattviz.plotting as pv\n"
        "from pyscattviz.dataio import common_prefix_suffix, read_curve, short_label"
    )
    settings = (
        f"x_column = {_literal(x_column)}      # None picks q_ca / q automatically\n"
        f"y_column = {_literal(y_column)}\n"
        f"normalization = {_literal(normalization)}   # none | maximum | integral | at x\n"
        f"reference_x = {_literal(reference_x)}       # used by the 'at x' normalization\n"
        f"offset = {_literal(offset)}                 # added to curve n\n"
        f"multiplier = {_literal(multiplier)}         # curve n is scaled by multiplier ** n\n"
        f"x_min, x_max = {_literal(x_min)}, {_literal(x_max)}"
    )
    body = '''
def normalize(y, x):
    """Scale one curve the way the GUI does."""
    y = np.asarray(y, dtype=float)
    if normalization == "maximum":
        scale = np.nanmax(np.abs(y))
    elif normalization == "integral":
        scale = abs(np.trapz(y, x))
    elif normalization == "at x":
        scale = abs(y[int(np.argmin(np.abs(np.asarray(x, float) - reference_x)))])
    else:
        return y
    return y / scale if np.isfinite(scale) and scale > 0 else y


curves = [read_curve(path, x_column, y_column) for path in paths]

# Legends of beamline stems are unreadable until the shared text is trimmed.
prefix, suffix = common_prefix_suffix([curve["label"] for curve in curves])

fig, ax = plt.subplots(figsize=(7, 5))
for index, curve in enumerate(curves):
    x, y = curve["x"], curve["y"]
    keep = np.ones(x.shape, dtype=bool)
    if x_min is not None:
        keep &= x >= x_min
    if x_max is not None:
        keep &= x <= x_max
    x, y = x[keep], normalize(curve["y"][keep], x[keep])
    y = y * (multiplier ** index) + index * offset
    ax.plot(x, y, lw=1.6, label=short_label(curve["label"], prefix, suffix))
'''.strip("\n")
    finish = (
        f"ax.set_xscale({_literal('log' if log_x else 'linear')})\n"
        f"ax.set_yscale({_literal('log' if log_y else 'linear')})\n"
        f"ax.set_xlabel({_literal(xlabel)})\n"
        f"ax.set_ylabel({_literal(ylabel)})\n"
        + (f"ax.set_title({_literal(title)})\n" if title else "")
        + "ax.legend(fontsize=8)\n"
        "fig.tight_layout()\n"
        "\n"
        "# pv.save_fig(fig, 'overlay.png', dpi=300)\n"
        "fig"
    )
    return _script(imports, "pv.set_theme('science')", _path_list(paths), settings, body, finish)


def stack_code(
    paths: Sequence[str],
    *,
    points: int = 600,
    log_x: bool = True,
    log_intensity: bool = True,
    x_min: float | None = None,
    x_max: float | None = None,
    cmap: str = "Turbo",
) -> str:
    """Return a script that builds the stacked intensity map."""

    imports = (
        "import matplotlib.pyplot as plt\n"
        "import numpy as np\n"
        "\n"
        "import pyscattviz.plotting as pv\n"
        "from pyscattviz.dataio import read_curve, stack_curves"
    )
    body = f"""
curves = [read_curve(path) for path in paths]
grid, labels, matrix = stack_curves(
    curves,
    points={points},
    x_min={_literal(x_min)},
    x_max={_literal(x_max)},
    log_x={log_x!r},
)

# matrix has one row per curve, interpolated onto the shared grid; points
# outside a curve's own range stay NaN rather than being extrapolated.
image = np.log10(np.where(matrix > 0, matrix, np.nan)) if {log_intensity!r} else matrix

fig, ax = plt.subplots(figsize=(8, 5))
mesh = ax.pcolormesh(grid, np.arange(len(labels)), image, cmap={_literal(matplotlib_cmap(cmap))}, shading="nearest")
ax.set_xscale({_literal("log" if log_x else "linear")})
ax.set_xlabel(curves[0]["x_name"])
ax.set_ylabel("curve")
ax.set_yticks(np.arange(len(labels)))
ax.set_yticklabels(labels, fontsize=6)
fig.colorbar(mesh, ax=ax, label={_literal("log I" if log_intensity else "I")})
fig.tight_layout()
fig
""".strip("\n")
    return _script(imports, "pv.set_theme('science')", _path_list(paths), body)


def image_code(
    path: str,
    array_name: str,
    *,
    log_intensity: bool = True,
    cmap: str = "Turbo",
    percentiles: tuple[float, float] = (1.0, 99.5),
    equal_aspect: bool = False,
    flip: bool = False,
) -> str:
    """Return a script that shows one 2D array or detector image."""

    imports = (
        "import matplotlib.pyplot as plt\n"
        "import numpy as np\n"
        "\n"
        "import pyscattviz.plotting as pv\n"
        "from pyscattviz.dataio import guess_kind, read_arrays, read_image"
    )
    body = f"""
path = {_literal(str(path))}
array_name = {_literal(array_name)}

if guess_kind(path) == "array":
    image = np.asarray(read_arrays(path)[array_name], dtype=float)
else:
    image = read_image(path)
{"image = np.flipud(image)" if flip else ""}

# Robust limits: one hot pixel must not flatten the whole picture.
finite = image[np.isfinite(image)]
vmin, vmax = np.nanpercentile(finite, {list(percentiles)})

fig = pv.imshow(
    image,
    log={log_intensity!r},
    cmap={_literal(matplotlib_cmap(cmap))},
    aspect={_literal("equal" if equal_aspect else "auto")},
    origin="lower",
    vmin=vmin,
    vmax=vmax,
    title=array_name,
)
fig
""".strip("\n")
    return _script(imports, body)


def publication_code(
    paths: Sequence[str],
    *,
    theme: str = "science",
    normalization: str = "none",
    q_min: float | None = None,
    q_max: float | None = None,
    offset: float = 0.0,
    log_x: bool = True,
    log_y: bool = True,
    title: str = "",
    figsize: tuple[float, float] = (7.0, 5.0),
    legend: bool = True,
) -> str:
    """Return a script that rebuilds the publication overlay."""

    imports = (
        "import matplotlib.pyplot as plt\n"
        "\n"
        "import pyscattviz.plotting as pv\n"
        "from pyscattviz.dataio import read_curve\n"
        "from pyscattviz.publication import Curve, build_curve_figure"
    )
    body = f"""
curves = []
for path in paths:
    data = read_curve(path)
    curves.append(Curve(data["label"], data["x"], data["y"]))

fig = build_curve_figure(
    curves,
    theme={_literal(theme)},
    normalization={_literal(normalization)},
    q_min={_literal(q_min)},
    q_max={_literal(q_max)},
    offset={_literal(offset)},
    logx={log_x!r},
    logy={log_y!r},
    title={_literal(title)},
    figsize={_literal(list(figsize))},
    legend={legend!r},
)

# pv.save_fig(fig, "figure.pdf")
fig
""".strip("\n")
    return _script(imports, _path_list(paths), body)


def frame_panel_code(
    root: str,
    stem: str,
    panel: str,
    *,
    cmap: str = "Turbo",
    log_intensity: bool = True,
    b_mode: str = "qx",
    log_q: bool = False,
) -> str:
    """Return a script that rebuilds one explorer panel for one frame."""

    imports = (
        "from pyscattviz.app.components.scattering import (\n"
        "    frame_axis_ranges,\n"
        "    frame_panel_figure,\n"
        "    index_frames,\n"
        ")"
    )
    body = f"""
root = {_literal(str(root))}
stem = {_literal(stem)}

# index_frames reads names only; nothing is opened until a panel is built.
frames = index_frames(root)
row = frames.set_index("stem").loc[stem]

print("this frame covers:", frame_axis_ranges(row, {_literal(b_mode)}))

figure, table, arrays = frame_panel_figure(
    row,
    {_literal(panel)},
    cmap={_literal(cmap)},
    logI={log_intensity!r},
    b_mode={_literal(b_mode)},
    logq={log_q!r},
    title=stem,
)
figure
""".strip("\n")
    return _script(imports, body)
