"""The code a page shows has to be code that runs.

A snippet that looks plausible and then raises on the first line is worse than
no snippet at all, so every generator is executed here against real files.
"""

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pytest

from pyscattviz.codegen import (
    curve_overlay_code,
    frame_panel_code,
    image_code,
    matplotlib_cmap,
    publication_code,
    stack_code,
)


@pytest.fixture(autouse=True)
def close_figures():
    yield
    plt.close("all")


@pytest.fixture
def dataset(tmp_path):
    """A result folder with the products the generators reference."""

    root = tmp_path / "giwaxs"
    (root / "cir_avg").mkdir(parents=True)
    (root / "q_image").mkdir()
    (root / "qphi").mkdir()

    q = np.logspace(-2, 0.4, 60)
    paths = []
    for index, name in enumerate(("sampleA_th0.1000deg", "sampleA_th0.1500deg")):
        target = root / "cir_avg" / f"Cir_Avg_{name}.tif.csv"
        pd.DataFrame({"q_ca": q, "iq_ca": (index + 1) * q**-2}).to_csv(target, index=False)
        paths.append(str(target))
        np.savez(
            root / "q_image" / f"qimg_{name}.tif.npz",
            qimg=np.abs(np.random.default_rng(index).normal(10, 2, (20, 25))),
            qx=np.linspace(-1, 4, 25),
            qz=np.linspace(-1, 5, 20),
        )
        np.savez(
            root / "qphi" / f"qphi_{name}.tif.npz",
            q=np.linspace(0.01, 7, 15),
            phi=np.linspace(-179, 179, 12),
            qphi=np.ones((12, 15)),
        )
    return root, paths


def _run(code: str) -> dict:
    namespace: dict = {}
    exec(compile(code, "<generated>", "exec"), namespace)  # noqa: S102 - that is the test
    return namespace


def test_the_overlay_script_runs_and_draws(dataset):
    _root, paths = dataset
    namespace = _run(curve_overlay_code(paths, normalization="maximum", title="two angles"))

    assert len(namespace["curves"]) == 2
    assert namespace["fig"].axes[0].get_xscale() == "log"
    assert namespace["fig"].axes[0].get_title() == "two angles"


@pytest.mark.parametrize("normalization", ["none", "maximum", "integral", "at x"])
def test_every_normalization_runs(normalization, dataset):
    _root, paths = dataset
    namespace = _run(curve_overlay_code(paths, normalization=normalization, reference_x=0.1))
    assert namespace["fig"] is not None


def test_the_overlay_script_honours_the_x_window(dataset):
    _root, paths = dataset
    namespace = _run(curve_overlay_code(paths, x_min=0.05, x_max=0.5))
    line = namespace["fig"].axes[0].lines[0]
    assert line.get_xdata().min() >= 0.05
    assert line.get_xdata().max() <= 0.5


def test_the_stack_script_runs(dataset):
    _root, paths = dataset
    namespace = _run(stack_code(paths, points=40))
    assert namespace["matrix"].shape == (2, 40)


def test_the_image_script_runs(dataset):
    root, _paths = dataset
    npz = next((root / "q_image").glob("*.npz"))
    namespace = _run(image_code(str(npz), "qimg", equal_aspect=True))
    assert namespace["image"].shape == (20, 25)


def test_the_publication_script_runs(dataset):
    _root, paths = dataset
    namespace = _run(publication_code(paths, theme="notebook", normalization="maximum"))
    assert len(namespace["curves"]) == 2
    assert namespace["fig"] is not None


def test_the_frame_panel_script_runs(dataset):
    root, _paths = dataset
    namespace = _run(frame_panel_code(str(root), "sampleA_th0.1000deg", "q_image"))
    assert namespace["figure"] is not None


@pytest.mark.parametrize("panel", ["q_image", "qphi", "cir_avg"])
def test_every_panel_script_runs(panel, dataset):
    root, _paths = dataset
    namespace = _run(frame_panel_code(str(root), "sampleA_th0.1500deg", panel))
    assert namespace["figure"] is not None


def test_a_plotly_colormap_becomes_a_matplotlib_one():
    """The 2D panels are Plotly; a generated script is matplotlib."""

    assert matplotlib_cmap("Turbo") == "turbo"
    assert matplotlib_cmap("Spectral") == "Spectral"
    # Plotly-only names must not be emitted verbatim; matplotlib would raise.
    assert matplotlib_cmap("Thermal") in plt.colormaps()
    assert matplotlib_cmap("Portland") in plt.colormaps()
    assert matplotlib_cmap("nothing like this") == "viridis"


def test_generated_scripts_are_self_contained(dataset):
    """Someone should be able to paste one into an empty notebook."""

    _root, paths = dataset
    for code in (
        curve_overlay_code(paths),
        stack_code(paths, points=30),
        publication_code(paths),
    ):
        assert code.startswith("# Generated by pyScattViz")
        assert "import" in code
        # The paths are written out, not referenced from the session.
        assert paths[0] in code


def test_paths_are_listed_one_per_line(dataset):
    _root, paths = dataset
    body = curve_overlay_code(paths)
    listed = [line for line in body.splitlines() if line.strip().startswith("'/")]
    assert len(listed) == len(paths)


def test_an_empty_selection_still_produces_valid_python():
    code = curve_overlay_code([])
    compile(code, "<generated>", "exec")
    assert "paths = []" in code
